apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
      - name: ocelot-api-gateway
        image: ayansonarcanys/k8s-f1-api-gateway:latest
        resources:
          requests:
            cpu: "100m"  # Minimum CPU
            memory: "128Mi"  # Minimum memory
          limits:
            cpu: "250m"  # Maximum CPU
            memory: "256Mi"  # Maximum memory
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway-srv
spec:
  type: NodePort
  selector:
    app: ocelot-api-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
