apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
stringData:
  SecretDefaultConnection: Server=mssql-clusterip-srv,1433;Initial Catalog=F1.DriversDB;TrustServerCertificate=True;User ID=sa;Password=passw0rd!;