apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_CONNECTION_STRING: "Server=myserver;Database=mydb;User Id=myuser;Password=mypassword;"
  API_URL: "https://api.example.com"
  ENVIRONMENT: "Development"
