apiVersion: v1
kind: Service
metadata:
  name: driverapinp-srv
spec:
  type: NodePort
  selector:
    app: driverapiservice
  ports:
    - name: driverapiservice
      protocol: TCP
      port: 8080
      targetPort: 8080