apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driverapiservice
  template:
    metadata:
      labels:
        app: driverapiservice
    spec:
      containers:
        - name: driverapiservice
          image: ayansonarcanys/k8s-f1driverapiservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: driverapi-srv
spec:
  type: ClusterIP
  selector:
    app: driverapiservice
  ports:
    - name: driverapiservice
      protocol: TCP
      port: 8080
      targetPort: 8080
