apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-api-service
  template:
    metadata:
      labels:
        app: driver-api-service
    spec:
      containers:
        - name: driver-api-service
          image: ayansonarcanys/k8s-f1-driver-api:latest
          env:
          - name: DB_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_CONNECTION_STRING
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: API_URL
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ENVIRONMENT
          resources:
            requests:
              cpu: "100m"  # Minimum CPU
              memory: "128Mi"  # Minimum memory
            limits:
              cpu: "250m"  # Maximum CPU
              memory: "256Mi"  # Maximum memory
---
apiVersion: v1
kind: Service
metadata:
  name: driver-api-srv
spec:
  type: ClusterIP
  selector:
    app: driver-api-service
  ports:
    - name: driver-api-service
      protocol: TCP
      port: 8080
      targetPort: 8080
